import { Prisma, UserRole } from "@prisma/client";
import { prisma } from "../lib/prisma";

const posts = [
  {
    title: "Mastering TypeScript Generics",
    content: "Generics provide a way to create reusable components...",
    isFeatured: true,
    status: "PUBLISHED",
    tags: ["typescript", "webdev"],
    views: 850,
  },
  {
    title: "Next.js 15 Server Actions Guide",
    content: "Server actions simplify the way we handle form submissions...",
    isFeatured: false,
    status: "PUBLISHED",
    tags: ["nextjs", "react"],
    views: 1200,
  },
  {
    title: "Prisma vs Drizzle: 2026 Comparison",
    content: "Choosing the right ORM depends on your type-safety needs...",
    isFeatured: false,
    status: "PUBLISHED",
    tags: ["database", "orm"],
    views: 940,
  },
  {
    title: "Dockerizing MERN Stack Apps",
    content: "Containerization ensures consistency across environments...",
    isFeatured: true,
    status: "PUBLISHED",
    tags: ["docker", "devops"],
    views: 720,
  },
  {
    title: "Advanced CSS Grid Techniques",
    content: "Grid layout has evolved with subgrid support...",
    isFeatured: false,
    status: "PUBLISHED",
    tags: ["css", "frontend"],
    views: 430,
  },
  {
    title: "Node.js Performance Tuning",
    content: "Optimizing the event loop can drastically reduce latency...",
    isFeatured: false,
    status: "PUBLISHED",
    tags: ["nodejs", "backend"],
    views: 1100,
  },
  {
    title: "State Management in 2026",
    content: "From Zustand to Signals, the landscape is shifting...",
    isFeatured: false,
    status: "PUBLISHED",
    tags: ["react", "javascript"],
    views: 670,
  },
  {
    title: "Building Scalable Microservices",
    content: "Microservices architecture requires robust communication...",
    isFeatured: true,
    status: "PUBLISHED",
    tags: ["architecture", "microservices"],
    views: 1500,
  },
  {
    title: "Secure Authentication with Better Auth",
    content: "A deep dive into session management and security...",
    isFeatured: false,
    status: "PUBLISHED",
    tags: ["auth", "security"],
    views: 890,
  },
  {
    title: "Redis Caching Strategies",
    content: "Caching is essential for high-traffic applications...",
    isFeatured: false,
    status: "PUBLISHED",
    tags: ["redis", "backend"],
    views: 560,
  },
  {
    title: "The Future of WebAssembly",
    content: "Wasm is moving beyond the browser into server-side...",
    isFeatured: true,
    status: "PUBLISHED",
    tags: ["wasm", "performance"],
    views: 310,
  },
  {
    title: "PostgreSQL Indexing Best Practices",
    content: "Proper indexing can speed up complex queries...",
    isFeatured: false,
    status: "PUBLISHED",
    tags: ["postgres", "database"],
    views: 980,
  },
  {
    title: "Testing React with Vitest",
    content: "Fast and lightweight testing for modern React apps...",
    isFeatured: false,
    status: "PUBLISHED",
    tags: ["testing", "react"],
    views: 450,
  },
  {
    title: "Git Workflow for Large Teams",
    content: "Rebase vs Merge: how to keep a clean history...",
    isFeatured: false,
    status: "PUBLISHED",
    tags: ["git", "workflow"],
    views: 770,
  },
  {
    title: "Introduction to TRPC",
    content: "End-to-end typesafe APIs without the boilerplate...",
    isFeatured: true,
    status: "PUBLISHED",
    tags: ["typescript", "api"],
    views: 640,
  },
  {
    title: "Tailwind CSS Design Systems",
    content: "Building a scalable UI kit using utility classes...",
    isFeatured: false,
    status: "PUBLISHED",
    tags: ["tailwind", "design"],
    views: 520,
  },
  {
    title: "Understanding Event-Driven Architecture",
    content: "Using message brokers like RabbitMQ or Kafka...",
    isFeatured: false,
    status: "PUBLISHED",
    tags: ["backend", "architecture"],
    views: 1300,
  },
  {
    title: "Edge Computing with Vercel",
    content: "Moving logic closer to the user for lower latency...",
    isFeatured: false,
    status: "PUBLISHED",
    tags: ["nextjs", "infrastructure"],
    views: 410,
  },
  {
    title: "GraphQL vs REST in 2026",
    content: "When to choose flexible schemas over fixed endpoints...",
    isFeatured: true,
    status: "PUBLISHED",
    tags: ["api", "graphql"],
    views: 920,
  },
  {
    title: "Clean Code Principles in JS",
    content: "Writing code that your future self will understand...",
    isFeatured: false,
    status: "PUBLISHED",
    tags: ["javascript", "coding"],
    views: 1800,
  },
  {
    title: "Zod Schema Validation",
    content: "Defining runtime types that sync with TypeScript...",
    isFeatured: false,
    status: "PUBLISHED",
    tags: ["typescript", "validation"],
    views: 590,
  },
  {
    title: "The Rise of Bun Runtime",
    content: "Bun is challenging Node.js with its integrated toolset...",
    isFeatured: true,
    status: "PUBLISHED",
    tags: ["runtime", "javascript"],
    views: 1400,
  },
  {
    title: "Responsive Images with Next/Image",
    content: "Optimizing LCP scores with modern image formats...",
    isFeatured: false,
    status: "PUBLISHED",
    tags: ["nextjs", "webperf"],
    views: 380,
  },
  {
    title: "MongoDB Aggregation Pipelines",
    content: "Processing large datasets directly in the database...",
    isFeatured: false,
    status: "PUBLISHED",
    tags: ["mongodb", "database"],
    views: 760,
  },
  {
    title: "Building a Personal Portfolio",
    content: "How to showcase your work effectively as a dev...",
    isFeatured: false,
    status: "PUBLISHED",
    tags: ["career", "webdev"],
    views: 2200,
  },
  {
    title: "Modern Redux with RTK Query",
    content: "Simplifying data fetching and state management...",
    isFeatured: true,
    status: "PUBLISHED",
    tags: ["react", "redux"],
    views: 510,
  },
  {
    title: "A Guide to Semantic HTML",
    content: "Improving accessibility and SEO with correct tags...",
    isFeatured: false,
    status: "PUBLISHED",
    tags: ["html", "seo"],
    views: 340,
  },
  {
    title: "Managing Monorepos with Turborepo",
    content: "Speed up your build times across multiple packages...",
    isFeatured: false,
    status: "PUBLISHED",
    tags: ["monorepo", "devops"],
    views: 680,
  },
  {
    title: "Serverless Functions on AWS",
    content: "Scaling backend logic without managing servers...",
    isFeatured: false,
    status: "PUBLISHED",
    tags: ["aws", "serverless"],
    views: 830,
  },
  {
    title: "Dependency Injection in NestJS",
    content: "Understanding the core concepts of NestJS modules...",
    isFeatured: true,
    status: "PUBLISHED",
    tags: ["nestjs", "backend"],
    views: 950,
  },
  {
    title: "Optimizing Core Web Vitals",
    content: "Steps to achieve a perfect 100 Lighthouse score...",
    isFeatured: false,
    status: "PUBLISHED",
    tags: ["webperf", "seo"],
    views: 1150,
  },
  {
    title: "Introduction to Shadcn/UI",
    content: "Beautifully designed components that you own...",
    isFeatured: false,
    status: "PUBLISHED",
    tags: ["react", "tailwind"],
    views: 2500,
  },
  {
    title: "Real-time Apps with Socket.io",
    content: "Building a chat application with websockets...",
    isFeatured: false,
    status: "PUBLISHED",
    tags: ["javascript", "realtime"],
    views: 740,
  },
  {
    title: "Functional Programming in JS",
    content: "Using map, filter, and reduce for cleaner code...",
    isFeatured: true,
    status: "PUBLISHED",
    tags: ["javascript", "fp"],
    views: 610,
  },
  {
    title: "Web Security Fundamentals",
    content: "Preventing XSS, CSRF, and SQL injection...",
    isFeatured: false,
    status: "PUBLISHED",
    tags: ["security", "webdev"],
    views: 1050,
  },
  {
    title: "Exploring the TanStack Query",
    content: "Powerful asynchronous state management for React...",
    isFeatured: false,
    status: "PUBLISHED",
    tags: ["react", "frontend"],
    views: 880,
  },
  {
    title: "The Impact of AI on Coding",
    content: "How LLMs are changing the software industry...",
    isFeatured: false,
    status: "PUBLISHED",
    tags: ["ai", "career"],
    views: 3200,
  },
  {
    title: "Elasticsearch for Devs",
    content: "Implementing fast full-text search in your app...",
    isFeatured: true,
    status: "PUBLISHED",
    tags: ["search", "backend"],
    views: 490,
  },
  {
    title: "Writing Better Git Commits",
    content: "The importance of conventional commit messages...",
    isFeatured: false,
    status: "PUBLISHED",
    tags: ["git", "pro-tips"],
    views: 630,
  },
  {
    title: "Deploying to Railway.app",
    content: "A simple alternative to Heroku for modern apps...",
    isFeatured: false,
    status: "PUBLISHED",
    tags: ["deployment", "cloud"],
    views: 570,
  },
  {
    title: "Next.js Middleware Explained",
    content: "Running code before a request is completed...",
    isFeatured: false,
    status: "PUBLISHED",
    tags: ["nextjs", "backend"],
    views: 820,
  },
  {
    title: "Testing with Playwright",
    content: "Reliable end-to-end testing for modern web apps...",
    isFeatured: true,
    status: "PUBLISHED",
    tags: ["testing", "qa"],
    views: 410,
  },
  {
    title: "Advanced React Hooks",
    content: "Creating custom hooks for complex logic...",
    isFeatured: false,
    status: "PUBLISHED",
    tags: ["react", "frontend"],
    views: 970,
  },
  {
    title: "CI/CD with GitHub Actions",
    content: "Automating your build, test, and deploy flow...",
    isFeatured: false,
    status: "PUBLISHED",
    tags: ["devops", "github"],
    views: 1020,
  },
  {
    title: "Using Pnpm for Faster Installs",
    content: "Why pnpm is superior to npm and yarn...",
    isFeatured: false,
    status: "PUBLISHED",
    tags: ["tools", "javascript"],
    views: 780,
  },
  {
    title: "Deep Dive into JSON Web Tokens",
    content: "How JWTs work and where to store them safely...",
    isFeatured: true,
    status: "PUBLISHED",
    tags: ["auth", "security"],
    views: 1450,
  },
  {
    title: "Building a Markdown Blog",
    content: "Using gray-matter and remark to parse content...",
    isFeatured: false,
    status: "PUBLISHED",
    tags: ["nextjs", "markdown"],
    views: 530,
  },
  {
    title: "The State of CSS in 2026",
    content: "Container queries, nesting, and new selectors...",
    isFeatured: false,
    status: "PUBLISHED",
    tags: ["css", "frontend"],
    views: 660,
  },
  {
    title: "Micro-frontends with Module Federation",
    content: "Scaling frontend development across teams...",
    isFeatured: false,
    status: "PUBLISHED",
    tags: ["architecture", "frontend"],
    views: 390,
  },
  {
    title: "Final Tips for Junior Devs",
    content: "Advice on landing your first tech role...",
    isFeatured: true,
    status: "PUBLISHED",
    tags: ["career", "mentorship"],
    views: 4000,
  },
];

async function seedPosts() {
  try {
    const author = await prisma.user.findFirst({
      where: { role: UserRole.ADMIN },
      select: { id: true },
    });

    if (!author) {
      return console.log("No admin found to assign posts to. Seed aborted.");
    }

    const postsData = posts.map((post) => ({
      ...post,
      thumbnail: null,
      authorId: author.id,
    })) as Prisma.PostCreateManyInput[];

    await prisma.post.createMany({
      data: postsData,
      skipDuplicates: true,
    });
  } catch (error: unknown) {
    console.error(error);
  } finally {
    await prisma.$disconnect();
  }
}

seedPosts();
